name: teramedik
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  get_storage: ^2.1.1
  map_launcher: ^2.5.0+1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/data.json
  fonts:
    - family: roboto
      fonts:
        - asset: assets/font/roboto.ttf
    - family: gabriola
      fonts:
        - asset: assets/font/gabriola.ttf
  uses-material-design: true
